### PR TITLE
SLING-11896 switch back to default Jenkins settings

### PR DESCRIPTION
**Pull request by joerghoh**

### CODE REVIEW

**Comment by joerghoh** [comment]
@rombert , @oliverlietz: Do you have a windows system ready to test this branch? The IntegrationTests are failing on windows now, but I cannot access the logs of the test; also I don't have access to any Windows system.

**Comment by rombert** [comment]
I don't have a Windows system around, maybe @stefanseifert can help?

**Comment by stefanseifert** [comment]
runs on my (windows) machine - jenkins reports green as well - is there an open issue?

**Comment by rombert** [comment]
I guess we should be good to go here then.

**Comment by joerghoh** [comment]
thanks for the confirmation.

**Pull request merged**
