### PR TITLE
workaround RB issue from depends-maven-plugin

### PR DESCRIPTION
**Pull request by hboutemy**
this is the only remaining issue to get a full repreoducible release: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/sling/org.apache.sling.servlets.resolver/README.md

### CODE REVIEW

**Comment by joerghoh** [comment]
@hboutemy thanks for this PR.

I would rather want to update the version the depends-maven-plugin in our poms (https://issues.apache.org/jira/browse/SLING-11907) and not try to workaround it on a per-bundle level.

**Comment by joerghoh** [comment]
@kwin yes, I assumed that the same process we use in Sling (closed ticket = part of a release) is also used in servicemix. Obviously it is not.

**Comment by hboutemy** [comment]
@joerghoh 1.5.0 release available https://repo1.maven.org/maven2/org/apache/servicemix/tooling/depends-maven-plugin/ :)

**Comment by joerghoh** [comment]
thanks @hboutemy , we included it into SLING parent 52 (SLING-11907).  I will update this bundle as soon as this version is released.

**Comment by hboutemy** [comment]
closing this PR as better replacement is https://github.com/apache/sling-parent/pull/35 / https://issues.apache.org/jira/browse/SLING-11907

**Pull request closed without merging**
